[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#2E8B57"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#262730"
font = "sans serif"
